version: '3.1'

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=languageassessmentpassword
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./upload:/app/upload