version: '3.1'

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4444:3000
    depends_on:
      - language_assesment_db
    volumes:
      - ./upload:/app/upload
    environment:
      DATABASE_URL: "postgresql://postgres:languageassessmentpassword@language_assesment_db:5432/postgres"


  language_assesment_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=languageassessmentpassword
      - POSTGRES_USER=postgres
    ports:
      - 5477:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

