version: '3.1'

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4444:3000
    depends_on:
      - language_assesment_db

  language_assesment_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=languageassessmentpassword
      - POSTGRES_USER=postgres
    ports:
      - 5437:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./upload:/app/upload